on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-25.04
    steps:

      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.10.0

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Build and run each test
        run: |
          sh scripts/runtests.sh
